version: '3'

services:
  db:
    image: arm64v8/mysql:oracle
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "127.0.0.1:3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./dbdata:/var/lib/mysql